// Code generated by Kitex v0.9.1. DO NOT EDIT.

package gate

import (
	server "github.com/cloudwego/kitex/server"
	gate "github.com/dobyte/due/transport/kitex/v2/internal/protocol/gate"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler gate.Gate, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
