package prometheus

const (
	ServerHandleDuration                          = "YAHAHA_server_handle_duration"
	CenterServerKickoffUser                       = "YAHAHA_center_server_kickoff_user"
	CenterServerBindGate                          = "YAHAHA_center_server_bind_gate"
	CenterServerLoginSuccess                      = "YAHAHA_center_server_login_success"
	CenterServerLoginFail                         = "YAHAHA_center_server_login_fail"
	CenterServerUserConnectAllocate               = "YAHAHA_center_server_user_connect_allocate"
	CenterServerAllocateFail                      = "YAHAHA_center_server_allocate_fail"
	CenterServerTotalOnlinePlayer                 = "YAHAHA_center_server_total_online_player"
	GateServerReceiveClientMessageCount           = "YAHAHA_gate_server_receive_client_message_count"
	GateServerReceiveClientMessageBytes           = "YAHAHA_gate_server_receive_client_message_bytes"
	GateServerSendToClientMessageCount            = "YAHAHA_gate_server_send_to_client_message_count"
	GateServerSendToClientMessageBytes            = "YAHAHA_gate_server_send_to_client_message_bytes"
	GateServerSendToServerMessageCount            = "YAHAHA_gate_server_send_to_server_message_count"
	GateServerReceiveFromServerMessageCount       = "YAHAHA_gate_server_receive_from_server_message_count"
	GateServerTotalOnlinePlayer                   = "YAHAHA_gate_server_total_online_player"
	GameServerUserOnline                          = "YAHAHA_game_server_user_online"
	GameServerUserOffline                         = "YAHAHA_game_server_user_offline"
	GameServerUnsendMessage                       = "YAHAHA_game_server_unsend_message"
	GameServerUnhandleMessage                     = "YAHAHA_game_server_unhandle_message"
	GameServerInterfaceResult                     = "YAHAHA_game_server_interface_result"
	CenterServerDrawTimeDuration                  = "YAHAHA_center_server_draw_time_duration"
	CenterServerDrawTotalCount                    = "YAHAHA_center_server_draw_total_count"
	CenterServerDrawWorldBallCount                = "YAHAHA_center_server_draw_world_ball_count"
	CenterServerDrawWorldBallLevel                = "YAHAHA_center_server_draw_world_ball_level"
	CenterServerDrawWorldBallExp                  = "YAHAHA_center_server_draw_world_ball_exp"
	CenterServerDungeonStartMatchCount            = "YAHAHA_center_server_dungeon_start_match_count"
	CenterServerDungeonMatchSuccessCount          = "YAHAHA_center_server_dungeon_match_success_count"
	CenterServerLuckDrawRequestCount              = "YAHAHA_center_server_luck_draw_request_count"
	CenterServerLuckDrawFinishedCount             = "YAHAHA_center_server_luck_draw_finished_count"
	CenterServerLuckDrawSuccessCount              = "YAHAHA_center_server_luck_draw_success_count"
	CenterServerLuckDrawAwardsRequire             = "YAHAHA_center_server_luck_draw_awards_require"
	CenterServerLuckDrawAwardsCurrentCount        = "YAHAHA_center_server_luck_draw_awards_current_count"
	CenterServerLuckDrawExtraDrawPoolSuccessCount = "YAHAHA_center_Server_luck_draw_extra_draw_pool_success_count"
	GateServerWriteError                          = "YAHAHA_gate_server_write_error"
	ServerInternalWriteError                      = "YAHAHA_server_internal_write_error"
	ServerReceiveHandleError                      = "YAHAHA_server_receive_handle_error"
	CenterServerLuckDrawTimeDuration              = "YAHAHA_center_server_luck_draw_time_duration"
	ServerRpcWriteDuration                        = "YAHAHA_server_rpc_write_duration"
	ServerRpcHandleDuration                       = "YAHAHA_server_rpc_handle_duration"
	GateServerWriteDuration                       = "YAHAHA_gate_server_write_duration"
)
