// Code generated by Kitex v0.9.1. DO NOT EDIT.

package node

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	node "github.com/dobyte/due/transport/kitex/v2/internal/protocol/node"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Trigger(ctx context.Context, req *node.TriggerRequest, callOptions ...callopt.Option) (r *node.TriggerResponse, err error)
	Deliver(ctx context.Context, req *node.DeliverRequest, callOptions ...callopt.Option) (r *node.DeliverResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNodeClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNodeClient struct {
	*kClient
}

func (p *kNodeClient) Trigger(ctx context.Context, req *node.TriggerRequest, callOptions ...callopt.Option) (r *node.TriggerResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Trigger(ctx, req)
}

func (p *kNodeClient) Deliver(ctx context.Context, req *node.DeliverRequest, callOptions ...callopt.Option) (r *node.DeliverResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Deliver(ctx, req)
}
