// Code generated by Kitex v0.9.1. DO NOT EDIT.

package node

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	node "github.com/dobyte/due/transport/kitex/v2/internal/protocol/node"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Trigger": kitex.NewMethodInfo(
		triggerHandler,
		newNodeTriggerArgs,
		newNodeTriggerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Deliver": kitex.NewMethodInfo(
		deliverHandler,
		newNodeDeliverArgs,
		newNodeDeliverResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	nodeServiceInfo                = NewServiceInfo()
	nodeServiceInfoForClient       = NewServiceInfoForClient()
	nodeServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return nodeServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return nodeServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return nodeServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Node"
	handlerType := (*node.Node)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "node",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func triggerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*node.NodeTriggerArgs)
	realResult := result.(*node.NodeTriggerResult)
	success, err := handler.(node.Node).Trigger(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNodeTriggerArgs() interface{} {
	return node.NewNodeTriggerArgs()
}

func newNodeTriggerResult() interface{} {
	return node.NewNodeTriggerResult()
}

func deliverHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*node.NodeDeliverArgs)
	realResult := result.(*node.NodeDeliverResult)
	success, err := handler.(node.Node).Deliver(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNodeDeliverArgs() interface{} {
	return node.NewNodeDeliverArgs()
}

func newNodeDeliverResult() interface{} {
	return node.NewNodeDeliverResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Trigger(ctx context.Context, req *node.TriggerRequest) (r *node.TriggerResponse, err error) {
	var _args node.NodeTriggerArgs
	_args.Req = req
	var _result node.NodeTriggerResult
	if err = p.c.Call(ctx, "Trigger", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Deliver(ctx context.Context, req *node.DeliverRequest) (r *node.DeliverResponse, err error) {
	var _args node.NodeDeliverArgs
	_args.Req = req
	var _result node.NodeDeliverResult
	if err = p.c.Call(ctx, "Deliver", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
