// Code generated by Kitex v0.9.1. DO NOT EDIT.
package node

import (
	server "github.com/cloudwego/kitex/server"
	node "github.com/dobyte/due/transport/kitex/v2/internal/protocol/node"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler node.Node, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler node.Node, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
