package node

import (
	"context"
	"testing"
	"time"

	"github.com/dobyte/due/v2/encoding"
)

// TestDefaultOptions verifies the default node options and the default values loaded from the
// environment are applied.
func TestDefaultOptions(t *testing.T) {
	o := defaultOptions()

	if o.ctx == nil {
		t.Fatal("ctx should not be nil")
	}
	if o.id == "" {
		t.Fatal("id should be generated by default")
	}
	if o.name != defaultName {
		t.Fatalf("expect name %q, got %q", defaultName, o.name)
	}
	if o.codec == nil || o.codec.Name() != defaultCodec {
		t.Fatalf("expect default codec %q, got %v", defaultCodec, o.codec)
	}
	if o.weight != defaultWeight {
		t.Fatalf("expect weight %d, got %d", defaultWeight, o.weight)
	}
	if o.addr != defaultAddr {
		t.Fatalf("expect addr %q, got %q", defaultAddr, o.addr)
	}
	if o.taskQueueSize != defaultTaskQueueSize {
		t.Fatalf("expect task queue size %d, got %d", defaultTaskQueueSize, o.taskQueueSize)
	}
	if o.messageQueueSize != defaultMessageQueueSize {
		t.Fatalf("expect message queue size %d, got %d", defaultMessageQueueSize, o.messageQueueSize)
	}
	if o.linker == nil {
		t.Fatal("linker options should not be nil")
	}
	if o.linker.connNum != defaultLinkerConnNum {
		t.Fatalf("expect conn num %d, got %d", defaultLinkerConnNum, o.linker.connNum)
	}
	if o.linker.callTimeout != time.Duration(3)*time.Second {
		t.Fatalf("expect call timeout 3s, got %v", o.linker.callTimeout)
	}
	if o.linker.dialTimeout != time.Duration(3)*time.Second {
		t.Fatalf("expect dial timeout 3s, got %v", o.linker.dialTimeout)
	}
	if o.linker.dialRetryTimes != defaultLinkerDialRetryTimes {
		t.Fatalf("expect dial retry times %d, got %d", defaultLinkerDialRetryTimes, o.linker.dialRetryTimes)
	}
	if o.linker.faultRecoveryTime != time.Duration(5)*time.Second {
		t.Fatalf("expect fault recovery time 5s, got %v", o.linker.faultRecoveryTime)
	}
	if o.linker.commandQueueSize != defaultLinkerCommandQueueSize {
		t.Fatalf("expect command queue size %d, got %d", defaultLinkerCommandQueueSize, o.linker.commandQueueSize)
	}
}

// TestNodeOptions verifies every With* option of the node.
func TestNodeOptions(t *testing.T) {
	codec := encoding.Invoke("json")
	locator := &stubLocator{}
	reg := &stubRegistry{}

	tests := []struct {
		name   string
		apply  func(o *options)
		assert func(t *testing.T, o *options)
	}{
		{
			name:  "WithID valid",
			apply: WithID("abc"),
			assert: func(t *testing.T, o *options) {
				if o.id != "abc" {
					t.Fatalf("expect id abc, got %s", o.id)
				}
			},
		},
		{
			name:  "WithID empty keeps the previous value",
			apply: WithID(""),
			assert: func(t *testing.T, o *options) {
				if o.id != "keep-id" {
					t.Fatalf("expect id keep-id, got %s", o.id)
				}
			},
		},
		{
			name:  "WithName valid",
			apply: WithName("myname"),
			assert: func(t *testing.T, o *options) {
				if o.name != "myname" {
					t.Fatalf("expect name myname, got %s", o.name)
				}
			},
		},
		{
			name:  "WithName empty keeps the previous value",
			apply: WithName(""),
			assert: func(t *testing.T, o *options) {
				if o.name != "keep-name" {
					t.Fatalf("expect name keep-name, got %s", o.name)
				}
			},
		},
		{
			name:  "WithAddr valid",
			apply: WithAddr("127.0.0.1:9000"),
			assert: func(t *testing.T, o *options) {
				if o.addr != "127.0.0.1:9000" {
					t.Fatalf("expect addr 127.0.0.1:9000, got %s", o.addr)
				}
			},
		},
		{
			name:  "WithAddr empty keeps the previous value",
			apply: WithAddr(""),
			assert: func(t *testing.T, o *options) {
				if o.addr != "keep-addr" {
					t.Fatalf("expect addr keep-addr, got %s", o.addr)
				}
			},
		},
		{
			name:  "WithExpose",
			apply: WithExpose(true),
			assert: func(t *testing.T, o *options) {
				if !o.expose {
					t.Fatal("expect expose true")
				}
			},
		},
		{
			name:  "WithCodec valid",
			apply: WithCodec(codec),
			assert: func(t *testing.T, o *options) {
				if o.codec != codec {
					t.Fatal("codec mismatch")
				}
			},
		},
		{
			name:  "WithCodec nil keeps the previous value",
			apply: WithCodec(nil),
			assert: func(t *testing.T, o *options) {
				if o.codec.Name() != defaultCodec {
					t.Fatalf("expect default codec, got %s", o.codec.Name())
				}
			},
		},
		{
			name:  "WithWeight valid",
			apply: WithWeight(5),
			assert: func(t *testing.T, o *options) {
				if o.weight != 5 {
					t.Fatalf("expect weight 5, got %d", o.weight)
				}
			},
		},
		{
			name:  "WithWeight not positive keeps the previous value",
			apply: WithWeight(0),
			assert: func(t *testing.T, o *options) {
				if o.weight != defaultWeight {
					t.Fatalf("expect default weight, got %d", o.weight)
				}
			},
		},
		{
			name:  "WithContext valid",
			apply: WithContext(newTestNodeCtx()),
			assert: func(t *testing.T, o *options) {
				if o.ctx == nil {
					t.Fatal("ctx should be set")
				}
			},
		},
		{
			name:  "WithContext nil keeps the previous value",
			apply: WithContext(nil),
			assert: func(t *testing.T, o *options) {
				if o.ctx == nil {
					t.Fatal("ctx should keep its previous value")
				}
			},
		},
		{
			name:  "WithLocator valid",
			apply: WithLocator(locator),
			assert: func(t *testing.T, o *options) {
				if o.locator != locator {
					t.Fatal("locator mismatch")
				}
			},
		},
		{
			name:  "WithLocator nil keeps the previous value",
			apply: WithLocator(nil),
			assert: func(t *testing.T, o *options) {
				if o.locator != nil {
					t.Fatal("locator should stay nil")
				}
			},
		},
		{
			name:  "WithRegistry valid",
			apply: WithRegistry(reg),
			assert: func(t *testing.T, o *options) {
				if o.registry != reg {
					t.Fatal("registry mismatch")
				}
			},
		},
		{
			name:  "WithRegistry nil keeps the previous value",
			apply: WithRegistry(nil),
			assert: func(t *testing.T, o *options) {
				if o.registry != nil {
					t.Fatal("registry should stay nil")
				}
			},
		},
		{
			name:  "WithEncryptor valid",
			apply: WithEncryptor(&stubEncryptor{}),
			assert: func(t *testing.T, o *options) {
				if o.encryptor == nil {
					t.Fatal("encryptor should be set")
				}
			},
		},
		{
			name:  "WithEncryptor nil keeps the previous value",
			apply: WithEncryptor(nil),
			assert: func(t *testing.T, o *options) {
				if o.encryptor != nil {
					t.Fatal("encryptor should stay nil")
				}
			},
		},
		{
			name:  "WithTransporter valid",
			apply: WithTransporter(&stubTransporter{}),
			assert: func(t *testing.T, o *options) {
				if o.transporter == nil {
					t.Fatal("transporter should be set")
				}
			},
		},
		{
			name:  "WithTransporter nil keeps the previous value",
			apply: WithTransporter(nil),
			assert: func(t *testing.T, o *options) {
				if o.transporter != nil {
					t.Fatal("transporter should stay nil")
				}
			},
		},
		{
			name:  "WithContextFunc valid",
			apply: WithContextFunc(newTestNodeCtx),
			assert: func(t *testing.T, o *options) {
				if o.ctxFunc == nil {
					t.Fatal("ctxFunc should be set")
				}
			},
		},
		{
			name:  "WithContextFunc nil keeps the previous value",
			apply: WithContextFunc(nil),
			assert: func(t *testing.T, o *options) {
				if o.ctxFunc != nil {
					t.Fatal("ctxFunc should stay nil")
				}
			},
		},
		{
			name:  "WithMetadata valid",
			apply: WithMetadata(map[string]string{"k": "v"}),
			assert: func(t *testing.T, o *options) {
				if o.metadata["k"] != "v" {
					t.Fatalf("expect metadata k=v, got %v", o.metadata)
				}
			},
		},
		{
			name:  "WithMetadata empty keeps the previous value",
			apply: WithMetadata(nil),
			assert: func(t *testing.T, o *options) {
				if len(o.metadata) != 0 {
					t.Fatalf("expect empty metadata, got %v", o.metadata)
				}
			},
		},
		{
			name:  "WithTaskQueueSize valid",
			apply: WithTaskQueueSize(128),
			assert: func(t *testing.T, o *options) {
				if o.taskQueueSize != 128 {
					t.Fatalf("expect task queue size 128, got %d", o.taskQueueSize)
				}
			},
		},
		{
			name:  "WithTaskQueueSize not positive keeps the previous value",
			apply: WithTaskQueueSize(0),
			assert: func(t *testing.T, o *options) {
				if o.taskQueueSize != defaultTaskQueueSize {
					t.Fatalf("expect default task queue size, got %d", o.taskQueueSize)
				}
			},
		},
		{
			name:  "WithTaskWriteTimeout valid",
			apply: WithTaskWriteTimeout(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.taskWriteTimeout != time.Second {
					t.Fatalf("expect 1s, got %v", o.taskWriteTimeout)
				}
			},
		},
		{
			name:  "WithTaskWriteTimeout negative keeps the previous value",
			apply: WithTaskWriteTimeout(-1),
			assert: func(t *testing.T, o *options) {
				if o.taskWriteTimeout != 0 {
					t.Fatalf("expect default task write timeout, got %v", o.taskWriteTimeout)
				}
			},
		},
		{
			name:  "WithMessageQueueSize valid",
			apply: WithMessageQueueSize(64),
			assert: func(t *testing.T, o *options) {
				if o.messageQueueSize != 64 {
					t.Fatalf("expect message queue size 64, got %d", o.messageQueueSize)
				}
			},
		},
		{
			name:  "WithMessageQueueSize not positive keeps the previous value",
			apply: WithMessageQueueSize(0),
			assert: func(t *testing.T, o *options) {
				if o.messageQueueSize != defaultMessageQueueSize {
					t.Fatalf("expect default message queue size, got %d", o.messageQueueSize)
				}
			},
		},
		{
			name:  "WithMessageWriteTimeout valid",
			apply: WithMessageWriteTimeout(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.messageWriteTimeout != time.Second {
					t.Fatalf("expect 1s, got %v", o.messageWriteTimeout)
				}
			},
		},
		{
			name:  "WithMessageWriteTimeout negative keeps the previous value",
			apply: WithMessageWriteTimeout(-1),
			assert: func(t *testing.T, o *options) {
				if o.messageWriteTimeout != 0 {
					t.Fatalf("expect default message write timeout, got %v", o.messageWriteTimeout)
				}
			},
		},
		{
			name:  "WithLinkerConnNum valid",
			apply: WithLinkerConnNum(9),
			assert: func(t *testing.T, o *options) {
				if o.linker.connNum != 9 {
					t.Fatalf("expect conn num 9, got %d", o.linker.connNum)
				}
			},
		},
		{
			name:  "WithLinkerConnNum not positive keeps the previous value",
			apply: WithLinkerConnNum(0),
			assert: func(t *testing.T, o *options) {
				if o.linker.connNum != defaultLinkerConnNum {
					t.Fatalf("expect default conn num, got %d", o.linker.connNum)
				}
			},
		},
		{
			name:  "WithLinkerCallTimeout valid",
			apply: WithLinkerCallTimeout(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.linker.callTimeout != time.Second {
					t.Fatalf("expect 1s, got %v", o.linker.callTimeout)
				}
			},
		},
		{
			name:  "WithLinkerCallTimeout negative keeps the previous value",
			apply: WithLinkerCallTimeout(-1),
			assert: func(t *testing.T, o *options) {
				if o.linker.callTimeout != 0 {
					t.Fatalf("expect default call timeout, got %v", o.linker.callTimeout)
				}
			},
		},
		{
			name:  "WithLinkerDialTimeout valid",
			apply: WithLinkerDialTimeout(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.linker.dialTimeout != time.Second {
					t.Fatalf("expect 1s, got %v", o.linker.dialTimeout)
				}
			},
		},
		{
			name:  "WithLinkerDialTimeout negative keeps the previous value",
			apply: WithLinkerDialTimeout(-1),
			assert: func(t *testing.T, o *options) {
				if o.linker.dialTimeout != 0 {
					t.Fatalf("expect default dial timeout, got %v", o.linker.dialTimeout)
				}
			},
		},
		{
			name:  "WithLinkerDialRetryTimes valid",
			apply: WithLinkerDialRetryTimes(5),
			assert: func(t *testing.T, o *options) {
				if o.linker.dialRetryTimes != 5 {
					t.Fatalf("expect 5 retries, got %d", o.linker.dialRetryTimes)
				}
			},
		},
		{
			name:  "WithLinkerDialRetryTimes negative keeps the previous value",
			apply: WithLinkerDialRetryTimes(-1),
			assert: func(t *testing.T, o *options) {
				if o.linker.dialRetryTimes != 0 {
					t.Fatalf("expect default retries, got %d", o.linker.dialRetryTimes)
				}
			},
		},
		{
			name:  "WithLinkerFaultRecoveryTime valid",
			apply: WithLinkerFaultRecoveryTime(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.linker.faultRecoveryTime != time.Second {
					t.Fatalf("expect 1s, got %v", o.linker.faultRecoveryTime)
				}
			},
		},
		{
			name:  "WithLinkerFaultRecoveryTime negative keeps the previous value",
			apply: WithLinkerFaultRecoveryTime(-1),
			assert: func(t *testing.T, o *options) {
				if o.linker.faultRecoveryTime != 0 {
					t.Fatalf("expect default fault recovery time, got %v", o.linker.faultRecoveryTime)
				}
			},
		},
		{
			name:  "WithLinkerCommandQueueSize valid",
			apply: WithLinkerCommandQueueSize(256),
			assert: func(t *testing.T, o *options) {
				if o.linker.commandQueueSize != 256 {
					t.Fatalf("expect 256, got %d", o.linker.commandQueueSize)
				}
			},
		},
		{
			name:  "WithLinkerCommandQueueSize not positive keeps the previous value",
			apply: WithLinkerCommandQueueSize(0),
			assert: func(t *testing.T, o *options) {
				if o.linker.commandQueueSize != 0 {
					t.Fatalf("expect default command queue size, got %d", o.linker.commandQueueSize)
				}
			},
		},
		{
			name:  "WithLinkerCommandWriteTimeout valid",
			apply: WithLinkerCommandWriteTimeout(time.Second),
			assert: func(t *testing.T, o *options) {
				if o.linker.commandWriteTimeout != time.Second {
					t.Fatalf("expect 1s, got %v", o.linker.commandWriteTimeout)
				}
			},
		},
		{
			name:  "WithLinkerCommandWriteTimeout negative keeps the previous value",
			apply: WithLinkerCommandWriteTimeout(-1),
			assert: func(t *testing.T, o *options) {
				if o.linker.commandWriteTimeout != 0 {
					t.Fatalf("expect default command write timeout, got %v", o.linker.commandWriteTimeout)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			o := &options{
				ctx:              context.Background(),
				id:               "keep-id",
				name:             "keep-name",
				addr:             "keep-addr",
				codec:            encoding.Invoke(defaultCodec),
				weight:           defaultWeight,
				taskQueueSize:    defaultTaskQueueSize,
				messageQueueSize: defaultMessageQueueSize,
				metadata:         make(map[string]string),
				linker:           &linkerOptions{connNum: defaultLinkerConnNum},
			}
			tt.apply(o)
			tt.assert(t, o)
		})
	}
}

// TestNodeOptionsApplyOnNewNode verifies that the With* options are applied by NewNode.
func TestNodeOptionsApplyOnNewNode(t *testing.T) {
	n := NewNode(
		WithID("id"),
		WithName("name"),
		WithAddr("127.0.0.1:0"),
		WithExpose(true),
		WithWeight(3),
		WithTaskQueueSize(16),
		WithMessageQueueSize(32),
		WithRegistry(&stubRegistry{}),
		WithLocator(&stubLocator{}),
	)

	if n.opts.id != "id" || n.opts.name != "name" || !n.opts.expose || n.opts.weight != 3 {
		t.Fatalf("options not applied: %+v", n.opts)
	}
	if n.opts.taskQueueSize != 16 || n.opts.messageQueueSize != 32 {
		t.Fatalf("queue sizes not applied: %+v", n.opts)
	}
}

// TestDefaultActorOptions verifies the default actor options.
func TestDefaultActorOptions(t *testing.T) {
	o := defaultActorOptions()

	if !o.wait {
		t.Fatal("wait should default to true")
	}
	if !o.dispatch {
		t.Fatal("dispatch should default to true")
	}
	if o.taskQueueSize != 1024 {
		t.Fatalf("expect task queue size 1024, got %d", o.taskQueueSize)
	}
	if o.messageQueueSize != 2048 {
		t.Fatalf("expect message queue size 2048, got %d", o.messageQueueSize)
	}
	if o.taskWriteTimeout != 3*time.Second {
		t.Fatalf("expect task write timeout 3s, got %v", o.taskWriteTimeout)
	}
	if o.messageWriteTimeout != 3*time.Second {
		t.Fatalf("expect message write timeout 3s, got %v", o.messageWriteTimeout)
	}
}

// TestActorOptions verifies every actor option.
func TestActorOptions(t *testing.T) {
	o := defaultActorOptions()

	WithActorID("id")(o)
	WithActorKind("kind")(o)
	WithActorArgs(1, "a")(o)
	WithActorArgs(true)(o)
	WithActorNonWait()(o)
	WithActorNonDispatch()(o)
	WithActorTaskQueueSize(8)(o)
	WithActorTaskWriteTimeout(time.Second)(o)
	WithActorMessageQueueSize(16)(o)
	WithActorMessageWriteTimeout(time.Second)(o)

	if o.id != "id" || o.kind != "kind" {
		t.Fatalf("id/kind not applied: %+v", o)
	}
	if len(o.args) != 3 {
		t.Fatalf("expect 3 args, got %d", len(o.args))
	}
	if o.wait {
		t.Fatal("wait should be false")
	}
	if o.dispatch {
		t.Fatal("dispatch should be false")
	}
	if o.taskQueueSize != 8 || o.messageQueueSize != 16 {
		t.Fatalf("queue sizes not applied: %+v", o)
	}
	if o.taskWriteTimeout != time.Second || o.messageWriteTimeout != time.Second {
		t.Fatalf("write timeouts not applied: %+v", o)
	}
}
