package rand

import (
	"crypto/rand"
	"encoding/binary"
	"math"
)

// TrueRandom is a true random number generator implemented on top of crypto/rand.
//
// It keeps no internal state and the underlying crypto/rand.Read is safe for concurrent use, so a
// TrueRandom is safe to share across goroutines.
type TrueRandom struct{}

var _ Random = (*TrueRandom)(nil)

// Int returns a non-negative true random integer.
func (r *TrueRandom) Int() int { return int(r.readUint64() >> 1) }

// IntN returns a non-negative true random integer in [0,n). n must be greater than 0.
func (r *TrueRandom) IntN(n int) int {
	if n <= 0 {
		panic("invalid argument to IntN")
	}
	return int(r.uint64n(uint64(n)))
}

// Int32 returns a non-negative true random 31-bit integer.
func (r *TrueRandom) Int32() int32 { return int32(r.readUint32() >> 1) }

// Int32N returns a non-negative true random 32-bit integer in [0,n). n must be greater than 0.
func (r *TrueRandom) Int32N(n int32) int32 {
	if n <= 0 {
		panic("invalid argument to Int32N")
	}
	return int32(r.uint32n(uint32(n)))
}

// Int64 returns a non-negative true random 63-bit integer.
func (r *TrueRandom) Int64() int64 { return int64(r.readUint64() >> 1) }

// Int64N returns a non-negative true random 64-bit integer in [0,n). n must be greater than 0.
func (r *TrueRandom) Int64N(n int64) int64 {
	if n <= 0 {
		panic("invalid argument to Int64N")
	}
	return int64(r.uint64n(uint64(n)))
}

// Uint returns a true random unsigned integer.
func (r *TrueRandom) Uint() uint { return uint(r.readUint64()) }

// UintN returns a non-negative true random unsigned integer in [0,n). n must be greater than 0.
func (r *TrueRandom) UintN(n uint) uint { return uint(r.uint64n(uint64(n))) }

// Uint32 returns a true random 32-bit unsigned integer.
func (r *TrueRandom) Uint32() uint32 { return r.readUint32() }

// Uint32N returns a non-negative true random 32-bit unsigned integer in [0,n). n must be greater
// than 0.
func (r *TrueRandom) Uint32N(n uint32) uint32 { return r.uint32n(n) }

// Uint64 returns a true random 64-bit unsigned integer.
func (r *TrueRandom) Uint64() uint64 { return r.readUint64() }

// Uint64N returns a non-negative true random 64-bit unsigned integer in [0,n). n must be greater
// than 0.
func (r *TrueRandom) Uint64N(n uint64) uint64 { return r.uint64n(n) }

// N returns a true random integer in [0,n) for any integer type. n must be greater than 0.
func (r *TrueRandom) N[Int intType](n Int) Int {
	if n <= 0 {
		panic("invalid argument to N")
	}
	return Int(r.uint64n(uint64(n)))
}

// Float32 returns a true random 32-bit float in [0.0,1.0).
func (r *TrueRandom) Float32() float32 { return float32(r.readUint32()>>8) / (1 << 24) }

// Float64 returns a true random 64-bit float in [0.0,1.0).
func (r *TrueRandom) Float64() float64 { return r.uniformFloat64() }

// ExpFloat64 returns a true random 64-bit float from an exponential distribution with rate
// parameter (lambda) 1 and mean 1, generated by inverse transform sampling.
func (r *TrueRandom) ExpFloat64() float64 {
	u := r.uniformFloat64()
	for u == 0 {
		u = r.uniformFloat64()
	}
	return -math.Log(u)
}

// NormFloat64 returns a true random 64-bit float from the standard normal distribution (mean 0,
// standard deviation 1), generated by transforming a uniform distribution with the Box-Muller
// method.
func (r *TrueRandom) NormFloat64() float64 {
	u1 := r.uniformFloat64()
	u2 := r.uniformFloat64()
	for u1 == 0 {
		u1 = r.uniformFloat64()
	}
	return math.Sqrt(-2*math.Log(u1)) * math.Cos(2*math.Pi*u2)
}

// Perm returns a true random permutation of the integers in [0,n).
func (r *TrueRandom) Perm(n int) []int {
	p := make([]int, n)
	for i := range p {
		p[i] = i
	}
	r.shuffle(len(p), func(i, j int) {
		p[i], p[j] = p[j], p[i]
	})
	return p
}

// Shuffle randomizes the order of the elements using swap. n is the number of elements and must
// not be negative.
func (r *TrueRandom) Shuffle(n int, swap func(i, j int)) {
	if n < 0 {
		panic("invalid argument to Shuffle")
	}
	r.shuffle(n, swap)
}

// readUint64 reads 8 bytes of random data from crypto/rand and converts them to a uint64.
func (*TrueRandom) readUint64() uint64 {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return binary.BigEndian.Uint64(b[:])
}

// readUint32 reads 4 bytes of random data from crypto/rand and converts them to a uint32.
func (*TrueRandom) readUint32() uint32 {
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err)
	}
	return binary.BigEndian.Uint32(b[:])
}

// uint64n returns a true random 64-bit unsigned integer in [0,n). It uses rejection sampling to
// avoid the modulo bias and keep the distribution uniform.
func (r *TrueRandom) uint64n(n uint64) uint64 {
	if n == 0 {
		panic("invalid argument to N")
	}

	if n&(n-1) == 0 {
		// When n is a power of two, masking already yields a uniform distribution.
		return r.readUint64() & (n - 1)
	}

	max := ^uint64(0) - (^uint64(0) % n)
	for {
		v := r.readUint64()
		if v < max {
			return v % n
		}
	}
}

// uint32n returns a true random 32-bit unsigned integer in [0,n). It uses rejection sampling to
// avoid the modulo bias and keep the distribution uniform.
func (r *TrueRandom) uint32n(n uint32) uint32 {
	if n == 0 {
		panic("invalid argument to N")
	}

	if n&(n-1) == 0 {
		return r.readUint32() & (n - 1)
	}

	max := ^uint32(0) - (^uint32(0) % n)
	for {
		v := r.readUint32()
		if v < max {
			return v % n
		}
	}
}

// uniformFloat64 returns a true random 64-bit float in [0.0,1.0).
func (r *TrueRandom) uniformFloat64() float64 {
	return float64(r.readUint64()>>11) / (1 << 53)
}

// shuffle shuffles the elements using the Fisher-Yates algorithm.
func (r *TrueRandom) shuffle(n int, swap func(i, j int)) {
	for i := n - 1; i > 0; i-- {
		j := int(r.uint64n(uint64(i + 1)))
		swap(i, j)
	}
}
