name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    strategy:
      matrix:
        go: [ "1.27.x" ]
    name: build & test
    runs-on: ubuntu-latest
    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.5.0
        ports:
          - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      consul:
        image: consul:1.12.3
        ports:
          - 8500:8500
      redis:
        image: redis:6.0
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

      - name: Coverage Summary
        run: go tool cover -func coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: false
